Pipelines v3 Release Candidate Testing
gruntwork-io/pipelines-workflows pull request #83
Opened 2024-08-29 16:10 UTC by ZachGoldberg

2024-09-27 15:49 UTC, yhakbar requested changes

2024-09-27 15:49 UTC, yhakbar commented on .github/workflows/pipelines-drift-detection.yml
> +        uses: gruntwork-io/pipelines-credentials@main
```suggestion
        uses: gruntwork-io/pipelines-credentials@v1
```

2024-09-27 15:49 UTC, yhakbar commented on .github/workflows/pipelines-drift-detection.yml
> +        uses: gruntwork-io/pipelines-credentials@main
```suggestion
        uses: gruntwork-io/pipelines-credentials@v1
```

2024-09-27 15:49 UTC, yhakbar commented on .github/workflows/pipelines-drift-detection.yml
> +        uses: gruntwork-io/pipelines-credentials@main
```suggestion
        uses: gruntwork-io/pipelines-credentials@v1
```

2024-09-27 15:49 UTC, yhakbar commented on .github/workflows/pipelines-drift-detection.yml
> +        uses: gruntwork-io/pipelines-credentials@main
```suggestion
        uses: gruntwork-io/pipelines-credentials@v1
```

2024-09-27 15:49 UTC, yhakbar commented on .github/workflows/pipelines-drift-detection.yml
> +        uses: gruntwork-io/pipelines-credentials@main
```suggestion
        uses: gruntwork-io/pipelines-credentials@v1
```

2024-09-27 15:49 UTC, yhakbar commented on .github/workflows/pipelines-drift-detection.yml
> +        uses: gruntwork-io/pipelines-credentials@main
```suggestion
        uses: gruntwork-io/pipelines-credentials@v1
```

2024-09-27 15:49 UTC, yhakbar commented on .github/workflows/pipelines-drift-detection.yml
> +        uses: gruntwork-io/pipelines-credentials@main
```suggestion
        uses: gruntwork-io/pipelines-credentials@v1
```

2024-09-27 15:49 UTC, yhakbar commented on .github/workflows/pipelines-root.yml
> +        uses: gruntwork-io/pipelines-credentials@main
```suggestion
        uses: gruntwork-io/pipelines-credentials@v1
```

2024-09-27 15:49 UTC, yhakbar commented on .github/workflows/pipelines-root.yml
> +        uses: gruntwork-io/pipelines-credentials@main
```suggestion
        uses: gruntwork-io/pipelines-credentials@v1
```

2024-09-27 15:49 UTC, yhakbar commented on .github/workflows/pipelines-root.yml
> +        uses: gruntwork-io/pipelines-credentials@main
```suggestion
        uses: gruntwork-io/pipelines-credentials@v1
```

2024-09-27 15:49 UTC, yhakbar commented on .github/workflows/pipelines-root.yml
> +        uses: gruntwork-io/pipelines-credentials@main
```suggestion
        uses: gruntwork-io/pipelines-credentials@v1
```

2024-09-27 15:49 UTC, yhakbar commented on .github/workflows/pipelines-root.yml
> +        uses: gruntwork-io/pipelines-credentials@main
```suggestion
        uses: gruntwork-io/pipelines-credentials@v1
```

2024-09-27 15:49 UTC, yhakbar commented on .github/workflows/pipelines-root.yml
> +        uses: gruntwork-io/pipelines-credentials@main
```suggestion
        uses: gruntwork-io/pipelines-credentials@v1
```

2024-09-27 15:49 UTC, yhakbar commented on .github/workflows/pipelines-root.yml
> +        uses: gruntwork-io/pipelines-credentials@main
```suggestion
        uses: gruntwork-io/pipelines-credentials@v1
```

2024-09-27 15:49 UTC, yhakbar commented on .github/workflows/pipelines-root.yml
> +        uses: gruntwork-io/pipelines-credentials@main
```suggestion
        uses: gruntwork-io/pipelines-credentials@v1
```

2024-09-27 15:49 UTC, yhakbar commented on .github/workflows/pipelines-root.yml
> +        uses: gruntwork-io/pipelines-credentials@main
```suggestion
        uses: gruntwork-io/pipelines-credentials@v1
```

2024-09-27 15:49 UTC, yhakbar commented on .github/workflows/pipelines-drift-detection.yml
> +  consolidate_jobs:
```suggestion
  consolidate_jobs:
  name: Consolidate Jobs
```

2024-09-27 15:49 UTC, yhakbar commented on .github/workflows/pipelines-unlock.yml
> +        uses: gruntwork-io/pipelines-credentials@main
```suggestion
        uses: gruntwork-io/pipelines-credentials@v1
```

2024-10-07 20:04 UTC, Resonance1584 commented on .github/workflows/pipelines-drift-detection.yml
> +  PIPELINES_CLI_VERSION: v0.29.0-rc17
```suggestion
  PIPELINES_CLI_VERSION: v0.29.0
```

2024-10-07 20:04 UTC, Resonance1584 commented on .github/workflows/pipelines-drift-detection.yml
> +  PIPELINES_ACTIONS_VERSION: v3-rc1
```suggestion
  PIPELINES_ACTIONS_VERSION: v3
```

2024-10-07 20:04 UTC, Resonance1584 commented on .github/workflows/pipelines-root.yml
> +  PIPELINES_CLI_VERSION: v0.29.0-rc17
```suggestion
  PIPELINES_CLI_VERSION: v0.29.0
```

2024-10-07 20:04 UTC, Resonance1584 commented on .github/workflows/pipelines-root.yml
> +  PIPELINES_ACTIONS_VERSION: v3-rc1
```suggestion
  PIPELINES_ACTIONS_VERSION: v3
```

2024-10-07 20:04 UTC, Resonance1584 commented on .github/workflows/pipelines-unlock.yml
> +  PIPELINES_CLI_VERSION: v0.29.0-rc17
```suggestion
  PIPELINES_CLI_VERSION: v0.29.0
```

2024-10-07 20:04 UTC, Resonance1584 commented on .github/workflows/pipelines-unlock.yml
> +  PIPELINES_ACTIONS_VERSION: v3-rc1
```suggestion
  PIPELINES_ACTIONS_VERSION: v3
```

2024-10-07 20:04 UTC, Resonance1584 commented on .github/workflows/pipelines.yml
> +  PIPELINES_CLI_VERSION: v0.29.0-rc17
```suggestion
  PIPELINES_CLI_VERSION: v0.29.0
```

2024-10-07 20:04 UTC, Resonance1584 commented on .github/workflows/pipelines.yml
> +  PIPELINES_ACTIONS_VERSION: v3-rc1
```suggestion
  PIPELINES_ACTIONS_VERSION: v3
```

2024-10-08 16:55 UTC, oredavids submitted a review, later dismissed

2024-10-08 16:55 UTC, oredavids commented on .github/workflows/pipelines-drift-detection.yml
> +      #
This documentation should be on the `runner` input. i.e move the `path` input

2024-10-08 17:05 UTC, yhakbar approved these changes

2024-10-08 17:05 UTC, yhakbar commented on .github/workflows/pipelines-root.yml
> +          step_name_prefix: "${{ steps.gruntwork_context.outputs.action == 'TERRAGRUNT_EXECUTE' && '[TerragruntExecute]:\ Authenticate with AWS and then Invoke Terragrunt' || (steps.gruntwork_context
NIT: This should be refactored out at some point. It's hard how this resolves on first inspection.

2024-10-08 17:09 UTC, merged